#!/bin/sh
# tools/spurarm/corpus/sample_grader_check.sh
#
# Randomly sample N pairs from a JSONL corpus, extract the script,
# build a tmp bench row that mirrors the world+expected, and feed
# the pair to tools/robot/grader.rail. Prints pass count + verdict.
#
# Usage:
#   sh tools/spurarm/corpus/sample_grader_check.sh <jsonl> [N]

set -u
JSONL="${1:?usage: sample_grader_check.sh <jsonl> [N]}"
N="${2:-50}"
TMP_BENCH="/tmp/spurarm_sample_bench.txt"
TMP_SCRIPTS_DIR="/tmp/spurarm_sample_scripts"
mkdir -p "$TMP_SCRIPTS_DIR"
rm -f "$TMP_SCRIPTS_DIR"/* 2>/dev/null

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq required" >&2
  exit 2
fi

# Sample N lines.
total_lines=$(wc -l < "$JSONL")
if [ "$total_lines" -lt "$N" ]; then
  N="$total_lines"
fi

# shuf may not be on macOS; use awk-based reservoir.
shuffle_lines() {
  awk -v n="$1" 'BEGIN{srand()} {a[NR]=$0} END{
    cnt=NR; for (i=0;i<n && cnt>0;i++) { r=int(rand()*cnt)+1; print a[r]; a[r]=a[cnt]; cnt--; }
  }' "$JSONL"
}

# Build a temporary bench file with one row per sample, using the
# sample's own world and expected. This lets us reuse grader.rail
# without modifying it.
: > "$TMP_BENCH"
echo "# auto-generated by sample_grader_check.sh" >> "$TMP_BENCH"

sample_idx=0
shuffle_lines "$N" > /tmp/spurarm_sample_lines.txt
while IFS= read -r line; do
  [ -z "$line" ] && continue
  sample_idx=$((sample_idx + 1))
  bid=$(printf 'sg%03d' "$sample_idx")
  nl=$(printf '%s' "$line" | jq -r '.nl')
  script=$(printf '%s' "$line" | jq -r '.script')
  obx=$(printf '%s' "$line" | jq -r '.world.obx')
  oby=$(printf '%s' "$line" | jq -r '.world.oby')
  obz=$(printf '%s' "$line" | jq -r '.world.obz')
  gex=$(printf '%s' "$line" | jq -r '.expected.gex')
  gey=$(printf '%s' "$line" | jq -r '.expected.gey')
  gez=$(printf '%s' "$line" | jq -r '.expected.gez')
  ggrip=$(printf '%s' "$line" | jq -r '.expected.ggrip')
  gheld=$(printf '%s' "$line" | jq -r '.expected.gheld')
  # bench format: id|nl|obx|oby|obz|gex|gey|gez|ggrip|gheld
  printf '%s|%s|%s|%s|%s|%s|%s|%s|%s|%s\n' \
    "$bid" "$nl" "$obx" "$oby" "$obz" "$gex" "$gey" "$gez" "$ggrip" "$gheld" >> "$TMP_BENCH"
  printf '%s\n' "$script" > "$TMP_SCRIPTS_DIR/$bid.rail"
done < /tmp/spurarm_sample_lines.txt

# grader.rail has bench_file hardcoded to tools/robot/bench_v0.txt; we
# need to temporarily swap. Use a temp bench by SYMLINKing through a
# wrapper grader instead -- but that means editing grader (frozen). The
# cleanest path: build_program in grader takes obx/oby/obz from the
# row; we can copy our temp bench file ON TOP of the existing one for
# the duration of the check, then restore.
ORIG_BENCH="tools/robot/bench_v0.txt"
BACKUP="/tmp/bench_v0_backup.txt"
cp "$ORIG_BENCH" "$BACKUP"
cat "$BACKUP" "$TMP_BENCH" > "$ORIG_BENCH"

pass=0
total=0
for f in "$TMP_SCRIPTS_DIR"/*.rail; do
  [ -e "$f" ] || break
  bid=$(basename "$f" .rail)
  total=$((total + 1))
  rm -f /tmp/rail_out /tmp/robot_sim_out.txt
  grade=$(./rail_native run tools/robot/grader.rail "$bid" "$f" 2>/dev/null | grep '^GRADE ' | head -1)
  st=$(printf '%s' "$grade" | sed -n 's/.*stage=\([0-9]*\).*/\1/p')
  if [ "${st:-0}" -ge 3 ]; then
    pass=$((pass + 1))
  else
    printf 'FAIL %s :: %s\n' "$bid" "$grade" >&2
  fi
done

# Restore original bench.
cp "$BACKUP" "$ORIG_BENCH"

pct=0
if [ "$total" -gt 0 ]; then pct=$(( pass * 100 / total )); fi
printf 'SAMPLE_GRADER_PASS_RATE pass=%d total=%d pct=%d\n' "$pass" "$total" "$pct"
