#!/bin/sh
# tools/spurarm/corpus/v2/sample_grader_check.sh
#
# Random sample N pairs from a JSONL corpus, feed each through
# tools/robot/grader.rail using a temporary bench row that mirrors
# its world+expected, and report the pass-rate-percent at stages >= 3.
#
# Port from v1 with no logic changes -- grader.rail is unchanged.
#
# Usage:
#   sh tools/spurarm/corpus/v2/sample_grader_check.sh <jsonl> [N]

set -u
JSONL="${1:?usage: sample_grader_check.sh <jsonl> [N]}"
N="${2:-50}"
TMP_BENCH="/tmp/spurarm_v2_sample_bench.txt"
TMP_SCRIPTS_DIR="/tmp/spurarm_v2_sample_scripts"
mkdir -p "$TMP_SCRIPTS_DIR"
rm -f "$TMP_SCRIPTS_DIR"/* 2>/dev/null

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq required" >&2
  exit 2
fi

total_lines=$(wc -l < "$JSONL")
if [ "$total_lines" -lt "$N" ]; then
  N="$total_lines"
fi

shuffle_lines() {
  awk -v n="$1" 'BEGIN{srand()} {a[NR]=$0} END{
    cnt=NR; for (i=0;i<n && cnt>0;i++) { r=int(rand()*cnt)+1; print a[r]; a[r]=a[cnt]; cnt--; }
  }' "$JSONL"
}

: > "$TMP_BENCH"
echo "# auto-generated by sample_grader_check.sh (v2)" >> "$TMP_BENCH"

sample_idx=0
shuffle_lines "$N" > /tmp/spurarm_v2_sample_lines.txt
while IFS= read -r line; do
  [ -z "$line" ] && continue
  sample_idx=$((sample_idx + 1))
  bid=$(printf 'sg%03d' "$sample_idx")
  nl=$(printf '%s' "$line" | jq -r '.nl')
  script=$(printf '%s' "$line" | jq -r '.script')
  obx=$(printf '%s' "$line" | jq -r '.world.obx')
  oby=$(printf '%s' "$line" | jq -r '.world.oby')
  obz=$(printf '%s' "$line" | jq -r '.world.obz')
  gex=$(printf '%s' "$line" | jq -r '.expected.gex')
  gey=$(printf '%s' "$line" | jq -r '.expected.gey')
  gez=$(printf '%s' "$line" | jq -r '.expected.gez')
  ggrip=$(printf '%s' "$line" | jq -r '.expected.ggrip')
  gheld=$(printf '%s' "$line" | jq -r '.expected.gheld')
  # Bench format (13 fields): id|nl|obx|oby|obz|gex|gey|gez|ggrip|gheld|gbx|gby|gbz
  # Sample records don't carry a separate ball-end position; we use the
  # same coord as obx/oby/obz so the grader's ball check is a no-op
  # when obx<0 (no ball in world) and otherwise expects ball stayed put.
  if [ "$obx" -lt 0 ] 2>/dev/null; then
    gbx="0"; gby="0"; gbz="0"
  else
    gbx="$obx"; gby="$oby"; gbz="$obz"
  fi
  printf '%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s\n' \
    "$bid" "$nl" "$obx" "$oby" "$obz" "$gex" "$gey" "$gez" "$ggrip" "$gheld" "$gbx" "$gby" "$gbz" >> "$TMP_BENCH"
  printf '%s\n' "$script" > "$TMP_SCRIPTS_DIR/$bid.rail"
done < /tmp/spurarm_v2_sample_lines.txt

ORIG_BENCH="tools/robot/bench_v0.txt"
BACKUP="/tmp/bench_v0_backup_v2.txt"
cp "$ORIG_BENCH" "$BACKUP"
cat "$BACKUP" "$TMP_BENCH" > "$ORIG_BENCH"

pass=0
total=0
for f in "$TMP_SCRIPTS_DIR"/*.rail; do
  [ -e "$f" ] || break
  bid=$(basename "$f" .rail)
  total=$((total + 1))
  rm -f /tmp/rail_out /tmp/robot_sim_out.txt
  grade=$(./rail_native run tools/robot/grader.rail "$bid" "$f" 2>/dev/null | grep '^GRADE ' | head -1)
  st=$(printf '%s' "$grade" | sed -n 's/.*stage=\([0-9]*\).*/\1/p')
  if [ "${st:-0}" -ge 3 ]; then
    pass=$((pass + 1))
  else
    printf 'FAIL %s :: %s\n' "$bid" "$grade" >&2
  fi
done

cp "$BACKUP" "$ORIG_BENCH"

pct=0
if [ "$total" -gt 0 ]; then pct=$(( pass * 100 / total )); fi
printf 'SAMPLE_GRADER_PASS_RATE pass=%d total=%d pct=%d\n' "$pass" "$total" "$pct"
